# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MiniLaunch < Formula
  desc "A simple cross-platform service daemon manager for macOS and Linux"
  homepage "https://github.com/simpossible/mini_launch"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/simpossible/mini_launch/releases/download/v0.1.0/mini_launch_0.1.0_darwin_x86_64.tar.gz"
      sha256 "99538d9b7074b3f30aa1f7e7f85cd85aa30d7b51dee2c44405414880cb0e8a22"

      define_method(:install) do
        bin.install "mini_launch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/simpossible/mini_launch/releases/download/v0.1.0/mini_launch_0.1.0_darwin_arm64.tar.gz"
      sha256 "ad78bf437589f40fd7decd074b365b39b745c659e05940457317ec011587ebda"

      define_method(:install) do
        bin.install "mini_launch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/simpossible/mini_launch/releases/download/v0.1.0/mini_launch_0.1.0_linux_x86_64.tar.gz"
      sha256 "b188c428737b896466ac69a714f36cbb18e6e658d45dc7a6fedfa16c5958dfe4"
      define_method(:install) do
        bin.install "mini_launch"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/simpossible/mini_launch/releases/download/v0.1.0/mini_launch_0.1.0_linux_arm64.tar.gz"
      sha256 "013a076e75614c26a64611fd4167f7d2c097bce06a8f77a2dfb11bf5983c5c2c"
      define_method(:install) do
        bin.install "mini_launch"
      end
    end
  end

  test do
    system "#{bin}/mini_launch", "--help"
  end
end
